### ISSUE TITLE
'click' undefined

### ISSUE THREAD

**Issue by nmcc1212** [sell/discord-autotyper#2]
I have just set up and when I ran ```node .``` I get this error,
```
/home/nial/discord-autotyper/discord.js:46
        await loginButton[1].click();
                             ^

TypeError: Cannot read property 'click' of undefined
    at Object.login (/home/nial/discord-autotyper/discord.js:46:30)
    at async /home/nial/discord-autotyper/index.js:9:5
```

**Comment by pahval** [comment]
same here...

**Comment by Beatsz** [comment]
yikes same in mine as well
